FILMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/movies/')),
    path('movies/', include('movies.urls')),
    path('magazines/', include('magazines.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:movie_id>/<int:review_id>/', views.detail, name='detail'),
    path('<int:movie_id>/<int:review_id>/delete', views.delete, name='delete'),
    path('<int:movie_id>/<int:review_id>/update', views.update, name='update'),
    path('<int:movie_id>/<int:review_id>/likes/', views.likes, name='likes'),
    path('<int:movie_id>/<int:review_id>/comments/', views.comments, name='comments'),
    path('<int:movie_id>/<int:review_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.
class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    rate = models.IntegerField(default=3)
    content = models.CharField(null=True, blank=True, max_length=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    content = forms.CharField(
        label = '리뷰 내용을 입력하세요',
        widget = forms.Textarea(
            attrs = {
                'class': 'form-control',
                'rows': 10,
            }
        ),
    )
    class Meta:
        model = Review
        fields = ('content',)

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label = '댓글 내용을 입력하세요',
        widget = forms.Textarea(
            attrs = {
                'class': 'form-control',
                'rows': 5,
            }
        ),
    )
    class Meta:
        model = Comment
        fields = ('content',)

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from movies.models import Movie
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request, movie_id):
    movie = Movie.objects.get(pk = movie_id)
    if request.method == "POST":
        if Review.objects.filter(user=request.user, movie=movie).exists():
            review_old = Review.objects.get(user=request.user, movie=movie)
            review_form = ReviewForm(request.POST, instance=review_old)
        else:
            review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.movie = movie
            review.rate = request.POST.get('rate')
            review.save()
            return redirect('movies:detail', movie.pk)

    else:
        review_form = ReviewForm()
    context = {
        'movie': movie,
        'review_form': review_form
    }
    return render(request, 'reviews/create.html', context)

def detail(request, movie_id, review_id):
    movie = Movie.objects.get(pk=movie_id)
    review = Review.objects.get(pk=review_id)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'reviews/detail.html', context)

def delete(request, movie_id, review_id):
    Review.objects.get(pk=review_id).delete()
    return redirect('movies:detail', movie_id)

def update(request, movie_id, review_id):
    movie = Movie.objects.get(pk=movie_id)
    review = Review.objects.get(pk=review_id)
    if request.method == "POST":
        update_form = ReviewForm(request.POST, instance=review)
        if update_form.is_valid():
            update_form.save(commit=False)
            update.user = request.user
            update.save()
            return redirect('reviews:detail', movie.pk, review.pk)
    else:
        update_form = ReviewForm(instance=review)
    context = {
        'update_form': update_form,
        'movie': movie,
        'review': review,
    }
    return render(request, 'reviews/update.html', context)

@login_required
def likes(request, movie_id, review_id):
    movie = Movie.objects.get(pk=movie_id)
    review = Review.objects.get(pk=review_id)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
    else:
        review.like_users.add(request.user)
    return redirect('reviews:detail', movie.pk, review.pk)

def comments(request, movie_id, review_id):
    movie = Movie.objects.get(pk=movie_id)
    review = Review.objects.get(pk=review_id)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.save()
        return redirect('reviews:detail', movie_id=movie_id, review_id=review_id)
    context = {
        'comment_form': comment_form,
        'movie': movie,
    }
    return render(request, 'reviews/detail.html', context)

def comment_delete(request, movie_id, review_id, comment_id):
    movie = Movie.objects.get(pk=movie_id)
    review = Review.objects.get(pk=review_id)
    Comment.objects.get(pk=comment_id).delete()
    return redirect('reviews:detail', movie.pk, review.pk)

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
  #myform fieldset{
    display: inline-block;
    direction: rtl;
    border:0;
  }
  #myform fieldset legend{
      text-align: right;
  }
  #myform input[type=radio]{
      display: none;
  }
  #myform label{
      font-size: 3em;
      color: transparent;
      text-shadow: 0 0 0 #f0f0f0;
  }
  #myform label:hover{
      text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
  }
  #myform label:hover ~ label{
      text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
  }
  #myform input[type=radio]:checked ~ label{
      text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
  }
  #reviewContents {
      width: 100%;
      height: 150px;
      padding: 10px;
      box-sizing: border-box;
      border: solid 1.5px #D3D3D3;
      border-radius: 5px;
      font-size: 16px;
      resize: none;
  }
</style>
{% endblock style %}

{% block content %}
<form action="{% url 'reviews:create' movie.pk %}" name="myform" id="myform" method="POST">
  {% csrf_token %}
  {% for field in review_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <fieldset>
    <span class="text-bold">별점을 선택해주세요</span>
    <input type="radio" name="rate" value="5" id="rate1"><label
        for="rate1">★</label>
    <input type="radio" name="rate" value="4" id="rate2"><label
        for="rate2">★</label>
    <input type="radio" name="rate" value="3" id="rate3"><label
        for="rate3">★</label>
    <input type="radio" name="rate" value="3" id="rate4"><label
        for="rate4">★</label>
    <input type="radio" name="rate" value="2" id="rate5"><label
        for="rate5">★</label>
  </fieldset>
  <div class="d-grid gap-2 mb-2">
    <input type="submit" class="btn btn-primary" value="CREATE">
  </div>
</form>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<div class="card mb-3">
  <ul class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div class="d-flex gap-2 align-items-center">
      {{ review.user }} {{ review.rate }}점 / 좋아요 {{ review.like_users.all.count }}개
      <form action="{% url 'reviews:likes' movie.pk review.pk %}" method=="POST">
        {% csrf_token %}
        {% if user in review.like_users.all %}
        <input type="submit" class="btn" value="NOT LIKE">
        {% else %}
        <input type="submit" class="btn" value="LIKE">
        {% endif %}
      </form>
      </div>
      <span>{{ review.created_at }}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">{{review.content}}</li>
  </ul>
</div>
{% if user.is_authenticated %}
<form action="{% url 'reviews:comments' movie.pk review.pk %}" method="POST">
  {% csrf_token %}
  {% for field in comment_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <div class="d-grid gap-2 mb-3">
    <input type="submit" class="btn" value="CREATE">
  </div>
</form>
{% endif %}
<div class="card mb-3">
  <ul class="list-group list-group-flush">
    {% for comment in comments %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      {{ comment.user }} : {{ comment.content }}
      <span>
        {% if comment.user == request.user %}
        <form action="{% url 'reviews:comment_delete' movie.pk review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input class="btn" type="submit" value="DELETE">
        </form>
        {% endif %}
      </span>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<form action="{% url 'reviews:update' movie.pk review.pk %}" method="POST">
  {% csrf_token %}
  {% for field in update_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <div class="d-grid gap-2 mb-2">
    <input type="submit" class="btn btn-primary" value="UPDATE">
  </div>
</form>
{% endblock content %}