FILMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/movies/')),
    path('movies/', include('movies.urls')),
    path('magazines/', include('magazines.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

magazines/urls.py
from django.urls import path
from . import views

app_name = 'magazines'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:magazine_id>/', views.detail, name='detail'),
    path('<int:magazine_id>/delete/', views.delete, name='delete'),
    path('<int:magazine_id>/update/', views.update, name='update'),
    path('<int:magazine_id>/movie/', views.mgzn_movie, name='mgzn_movie'),
    path('<int:magazine_id>/movie/<int:movie_id>/delete/', views.mgzn_movie_delete, name='mgzn_movie_delete'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/delete/', views.delete, name='delete'),
    path('<int:movie_id>/update', views.update, name='update'),
    path('<int:movie_id>/person/', views.person, name='person'),
    path('<int:movie_id>/person/<int:person_id>/delete/', views.person_delete, name='person_delete'),
    path('<int:movie_id>/grouper_wsh/', views.grouper_wsh, name='grouper_wsh'),
    path('<int:movie_id>/wish/', views.wish, name='wish'),
    path('genre/<str:genre>', views.genre, name='genre'),
    path('country/<str:country>', views.country, name='country'),
    path('magazine/<int:magazine_id>', views.magazine, name='magazine'),
    path('every_movies/', views.every_movies, name='every_movies'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:movie_id>/<int:review_id>/', views.detail, name='detail'),
    path('<int:movie_id>/<int:review_id>/delete', views.delete, name='delete'),
    path('<int:movie_id>/<int:review_id>/update', views.update, name='update'),
    path('<int:movie_id>/<int:review_id>/likes/', views.likes, name='likes'),
    path('<int:movie_id>/<int:review_id>/comments/', views.comments, name='comments'),
    path('<int:movie_id>/<int:review_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

magazines/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from movies.models import Movie

# Create your models here.
class Magazine(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mgzn_title = models.CharField(max_length=50, null=True, blank=True)
    def image_path(instance, filename):
        return f'magazines/{instance.mgzn_title}/{filename}'
    cover = models.ImageField(upload_to=image_path)
    cover_thumbnail = ImageSpecField(source='cover',
                                      processors=[Thumbnail(200, 260)],
                                      format='JPEG',
                                      options={'quality': 100})
    publish_date = models.DateField(null=True, blank=True)
    official = models.URLField(null=True, blank=True)
    where_to_buy = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class MagazineMovie(models.Model):
    magazine = models.ForeignKey(Magazine, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

reviews/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.
class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    rate = models.IntegerField(default=3)
    content = models.CharField(null=True, blank=True, max_length=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

magazines/forms.py
from .models import Magazine, MagazineMovie
from movies.models import Movie
from django import forms

class MagazineForm(forms.ModelForm):
    mgzn_title = forms.CharField(
        label = '잡지명',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '잡지명을 입력하세요',
            }
        )
    )
    cover = forms.ImageField(
        label = '잡지커버',
        widget = forms.ClearableFileInput(
            attrs = {
                'class': 'form-control',
                'multiple': True,
            },
        ),
        required = False,
    )
    publish_date = forms.DateField(
        label = '발행일',
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        ),
    )
    official = forms.URLField(
        label = '공식 사이트',
        required = False,
        widget = forms.URLInput(
            attrs = {
                'class': 'form-control'
            }
        )
    )
    where_to_buy = forms.URLField(
        label = '구매처',
        required = False,
        widget = forms.URLInput(
            attrs = {
                'class': 'form-control'
            }
        )
    )
    class Meta:
        model = Magazine
        fields = ('mgzn_title', 'cover', 'publish_date','official', 'where_to_buy')

class MagazineMovieForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        queryset=Movie.objects.all(),
        to_field_name='title'
    )
    class Meta:
        model = MagazineMovie
        fields = ('movie',)

movies/forms.py
from django import forms
from .models import Movie, MoviePeople, MoviePhoto

class MovieForm(forms.ModelForm):
    title = forms.CharField(
        label = '영화 제목',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '영화 제목을 입력하세요',
            }
        )
    )
    original_title = forms.CharField(
        label = '영화 원제',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '영화 원제를 입력하세요',
            }
        )
    )
    poster = forms.ImageField(
        label = '포스터',
        widget = forms.ClearableFileInput(
            attrs = {
                'class': 'form-control',
                'multiple': True,
            },
        ),
        required = False,
    )
    release_date = forms.DateField(
        label = '개봉일',
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        ),
    )
    genre = forms.CharField(
        label = '영화 장르',
        widget = forms.Select(
            attrs = {
                'class': 'form-control',
            },
        choices = [
            ("드라마", "드라마"),
            ("판타지", "판타지"),
            ("서부", "서부"),
            ("공포", "공포"),
            ("로맨스", "로맨스"),
            ("모험", "모험"),
            ("스릴러", "스릴러"),
            ("느와르", "느와르"),
            ("컬트", "컬트"),
            ("다큐멘터리", "다큐멘터리"),
            ("코미디", "코미디"),
            ("가족", "가족"),
            ("미스터리", "미스터리"),
            ("전쟁", "전쟁"),
            ("애니메이션", "애니메이션"),
            ("범죄", "범죄"),
            ("뮤지컬", "뮤지컬"),
            ("SF", "SF"),
            ("액션", "액션"),
            ("무협", "무협"),
            ("에로", "에로"),
            ("서스펜스", "서스펜스"),
            ("서사", "서사"),
            ("블랙코미디", "블랙코미디"),
            ("실험", "실험"),
            ("영화카툰", "영화카툰"),
            ("영화음악", "영화음악"),
            ("영화패러디포스터", "영화패러디포스터"),
        ]
        ),
    )
    country = forms.CharField(
        label = '영화 국가',
        widget = forms.Select(
            attrs = {
                'class': 'form-control',
            },
        choices = [
            ("프랑스", "프랑스"),
            ("영국", "영국"),
            ("홍콩", "홍콩"),
            ("일본", "일본"),
            ("한국", "한국"),
            ("미국", "미국"),
            ("기타", "기타"),
        ]
        ),
    )
    running_time  = forms.CharField(
        label = '러닝 타임',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '러닝 타임을 입력하세요',
            }
        )
    )
    age = forms.CharField(
        label = '연령',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '연령을 입력하세요',
            }
        )
    )
    class Meta:
        model = Movie
        fields = ('title', 'original_title', 'release_date', 'genre', 'country', 'running_time', 'age', 'poster')

class MoviePeopleForm(forms.ModelForm):
    person_name = forms.CharField(
        label = '이름',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '이름을 입력하세요',
            }
        )
    )
    part = forms.CharField(
        label = '역할',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '역할을 입력하세요',
            }
        )
    )
    character_name = forms.CharField(
        label = '캐릭터명',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '캐릭터명을 입력하세요',
            }
        ),
        required=False,
    )
    person_photo = forms.ImageField(
        label = '프로필 사진',
        widget = forms.ClearableFileInput(
            attrs = {
                'class': 'form-control',
                'multiple': True,
            },
        ),
        required = False,
    )
    class Meta:
        model = MoviePeople
        fields = ('person_name', 'part', 'character_name', 'person_photo')

class MoviePhotoForm(forms.ModelForm):
    image_movie = forms.ImageField(
        label = '무비 포토',
        widget = forms.ClearableFileInput(
            attrs = {
                'class': 'form-control',
                'multiple': True,
            },
        ),
        required = False,
    )
    class Meta:
        model = MoviePhoto
        fields = ('image_movie',)

magazines/views.py
from django.shortcuts import render, redirect
from .models import Magazine, MagazineMovie, Movie
from .forms import MagazineForm, MagazineMovieForm

# Create your views here.
def create(request):
    if request.method == "POST":
        magazine_form = MagazineForm(request.POST, request.FILES)
        if magazine_form.is_valid():
            magazine = magazine_form.save(commit=False)
            magazine.user = request.user
            magazine.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        magazine_form = MagazineForm()
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
        
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine_form': magazine_form,
    }
    return render(request, 'magazines/create.html', context)

def detail(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    movies = magazine.magazinemovie_set.all()
    mgzn_movies = [movie.movie for movie in movies]
    movies_country = Movie.objects.all().order_by('country')
    movies_genre = Movie.objects.all().order_by('genre')
    magazines = Magazine.objects.all()
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine': magazine,
        'mgzn_movies': mgzn_movies,
    }
    return render(request, 'magazines/detail.html', context)

def delete(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.user == magazine.user:
        magazine.delete()
    return redirect('movies:index')

def update(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.method == "POST":
        update_form = MagazineForm(request.POST, request.FILES, instance=magazine)
        if update_form.is_valid():
            update = update_form.save(commit=False)
            update.user = request.user
            update.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        update_form = MagazineForm(instance=magazine)
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'update_form': update_form,
        'magazine': magazine,
    }
    return render(request, 'magazines/update.html', context)
    

def mgzn_movie(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.method=="POST":
        mgzn_movie_form = MagazineMovieForm(request.POST)
        if mgzn_movie_form.is_valid():
            mgzn_movie = mgzn_movie_form.save(commit=False)
            mgzn_movie.magazine = magazine
            mgzn_movie.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        mgzn_movie_form = MagazineMovieForm()
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
        
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine': magazine,
        'mgzn_movie_form': mgzn_movie_form,
    }
    return render(request, 'magazines/mgzn_movie.html', context)

def mgzn_movie_delete(request, magazine_id, movie_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    mgzn_movie = MagazineMovie.objects.get(movie_id=movie_id)
    if request.user == magazine.user:
        mgzn_movie.delete()
    return redirect('magazines:detail', magazine.pk)

movies/templates/movies/country.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'movies/css/country_style.css' %}">
{% endblock style %}

{% block content %}
  <header class="d-flex justify-content-center align-items-center text-center border-bottom">
    <div>
      <h5 class="update__info mt-4">업데이트 정보 : 
        <script type="text/javascript">
          document.write(getTimeStamp() + '<br />');

          function getTimeStamp() {
            var d = new Date();
          
            var s =
              leadingZeros(d.getFullYear(), 4) + '-' +
              leadingZeros(d.getMonth() + 1, 2) + '-' +
              leadingZeros(d.getDate(), 2) + ' ' +
          
              leadingZeros(d.getHours(), 2) + ':' +
              leadingZeros(d.getMinutes(), 2) + ':' +
              leadingZeros(d.getSeconds(), 2);
          
            return s;
          }
          
          function leadingZeros(n, digits) {
            var zero = '';
            n = n.toString();
          
            if (n.length < digits) {
              for (i = 0; i < digits - n.length; i++)
                zero += '0';
            }
            return zero + n;
          }
        </script>
      </h5>
      <h1 class="mt-3 mb-5">베스트 {{ country }} 영화 </h1>
    </div>
  </header>
  {% for movie in movies %}
    <div class="container">
      <div class="row justify-content-center mt-3 mb-3">
        <div class="col-12 col-lg-3">
          <div class="container__img float-end">
          {% if movie.poster_thumbnail %}
            <a href="{% url 'movies:detail' movie.pk %}"><img class="movie__img align-self-center" src="{{ movie.poster_thumbnail.url }}" alt=""></a>
          {% else %}
          {% endif %}
          </div>
        </div>
        <div class="info__parent col-12 col-lg-6" style="flex: 1; position: relative;">
          <div class="info__row row">
            <div class="info__first col-10">
              <h3><a class="movie__title text-decoration-none" href="{% url 'movies:detail' movie.pk %}">{{ forloop.counter }}. {{ movie.title }}<span class="span__rate"> {{ movie.rate|floatformat:1 }}</span></a></h3>
              <h5>{{ movie.release_date }}</h5>
            </div>
            <div class="info__second text-end col-2">
              {% if movie.user == user %}
              {% else %}
              <form action="{% url 'movies:grouper_wsh' movie.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in movie.wish_users.all %}
                  <input type="submit" value="NOT WISH" class="btn btn-primary">
                {% else %}
                  <input type="submit" value="WISH" class="btn btn-primary">
                {% endif %}
              </form>
              {% endif %}
              {% comment %} <form id="wish-form" data-movie-id="{{ movie.pk }}">
                {% csrf_token %}
                {% if request.user in movie.wish_users.all %}
                  <input type="submit" value="NOT WISH" class="btn btn-primary" style="background-color: #ff7001; border-color: #ff7001;">
                {% else %}
                  <input type="submit" value="WISH" class="btn btn-primary" style="background-color: #ff7001; border-color: #ff7001;">
                {% endif %}
              </form> {% endcomment %}
            </div>
          </div>
          {% with first_review=movie.review_set.all|first %}
            {% if first_review.content %}
              <div class="info__third box">
                {{ first_review.user }} : {{ first_review.content }}
              </div>
            {% endif %}
          {% endwith %}
          <div class="info__fourth text-end">
            <a class="text-decoration-none" href="{% url 'movies:detail' movie.pk %}">{{ movie.title }} 정보 더보기 ></a>
          </div>
        </div>
      </div>
      <hr class="divider w-100">
    </div>
  {% endfor %}
{% endblock content %}

{% comment %} {% block script %}
<script>
  const form = document.querySelector('#wish-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  form.addEventListener('submit', function (event) {
    event.preventDefault()
    const movieId = event.target.dataset.movieId
    axios({
      method: 'post',
      url: `/movies/${movieId}/wish/`,
      headers: {'X-CSRFToken': csrftoken},
    })
      .then((response) => {
        const isWished = response.data.is_wished
        const wishBtn = document.querySelector('#wish-form > input[type=submit]')
        if (isWished === true) {
          wishBtn.value = 'NOT WISH'
        } else {
          wishBtn.value = 'WISH'
        }
      })
  })
</script>
{% endblock script %} {% endcomment %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'movies/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'movies/owl.theme.default.min.css' %}">
{% endblock head %}
{% block nav_bg %}
position: relative;

/* The image used */
color: white;
background-image: url({{ first_moviephoto }});

min-height: 380px;

/* Center and scale the image nicely */
background-position: top;
background-repeat: no-repeat;
background-size: cover;

/* Needed to position the navbar */
position: relative;
{% endblock nav_bg %}

{% block style %}
.nav__container {
  background-color: rgba(255, 255, 255, 0.7);
  position: fixed;
  top: 0; /* Position the child div at the top */
  left: 0; /* Position the child div at the left */
  width: 100%;
}

#myform fieldset{
  display: inline-block;
  direction: rtl;
  border:0;
}
#myform fieldset legend{
    text-align: right;
}
#myform input[type=radio]{
    display: none;
}
#myform label{
    font-size: 3em;
    color: transparent;
    text-shadow: 0 0 0 #f0f0f0;
}
#myform label:hover{
    text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
}
#myform label:hover ~ label{
    text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
}
#myform input[type=radio]:checked ~ label{
    text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);
}
#reviewContents {
    width: 100%;
    height: 150px;
    padding: 10px;
    box-sizing: border-box;
    border: solid 1.5px #D3D3D3;
    border-radius: 5px;
    font-size: 16px;
    resize: none;
}

{% endblock style %}

{% block content %}
<div class="row gap-3">
  <div class="card" style="width: 100%; padding: 0;">
    <div class="row">
      <div class="col-auto">
        <img class="card-img-top rounded" src="{{ movie.poster_thumbnail.url }}" alt="">
      </div>
      <div class="col">
        <h2 class="fw-bold">{{ movie.title }}</h2>
        <p style = "font-size: 13pt;">{{ movie.release_date.year }} ・ {{ movie.genre }} ・ {{ movie.country }} ・ 평균 평점 {{ movie.rate }}점</p>
        <div class="d-grid gap-2">
          {% if movie.user == user %}
          <form action="{% url 'movies:delete' movie.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE" class="btn">
          </form>
          <a href="{% url 'movies:update' movie.pk %}" class="btn">UPDATE</a>
          <a href="{% url 'movies:person' movie.pk %}" class="btn">PERSON</a>
          {% else %}
          <form name="myform" id="myform" method="POST" action="{% url 'movies:detail' movie.pk %}">
            {% csrf_token %}
            <fieldset>
              <span class="text-bold">별점을 선택해주세요</span>
              <input type="radio" name="rate" value="5" id="rate1"><label for="rate1">★</label>
              <input type="radio" name="rate" value="4" id="rate2"><label for="rate2">★</label>
              <input type="radio" name="rate" value="3" id="rate3"><label for="rate3">★</label>
              <input type="radio" name="rate" value="2" id="rate4"><label for="rate4">★</label>
              <input type="radio" name="rate" value="1" id="rate5"><label for="rate5">★</label>
            </fieldset>
            <button class="btn" type="submit">Save</button>
          </form>
          {% comment %} <div class="d-grid gap-2 d-flex" style="margin: 0; padding: 0;"> {% endcomment %}
          <a href="{% url 'reviews:create' movie.pk %}" class="btn">REVIEW</a>
          <form id="wish-form" data-movie-id="{{ movie.pk }}">
            {% csrf_token %}
            {% if user in movie.wish_users.all %}
            <input type="submit" value="NOT WISH" class="btn">
            {% else %}
            <input type="submit" value="WISH" class="btn">
            {% endif %}
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="info">
    <div class="info__basic">
      <h4>기본 정보</h4>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">원제 : {{ movie.original_title }}</li>
        <li class="list-group-item">개봉일 : {{ movie.release_date }}</li>
        <li class="list-group-item">장르 : {{ movie.genre }}</li>
        <li class="list-group-item">국가 : {{ movie.country }}</li>
        <li class="list-group-item">연령 : {{ movie.age }}</li>
      </ul>
    </div>
    {% if moviepeople %}
    <div class="info__person">
      <h4>인물 정보</h4>
      <div class="owl-carousel owl-theme">
        {% for person in moviepeople %}
        <div class="card" style="width: 13rem; padding: 0;">
          <ul class="list-group list-group-flush">
            <img class="card-img-top rounded" src="{{ person.personphoto_thumbnail.url }}" alt="" style="">
            <li class="list-group-item">이름 : {{ person.person_name }}</li>
            <li class="list-group-item">역할 : {{ person.part }}</li>
            {% if person.character_name %}
            <li class="list-group-item">캐릭터명 : {{ person.character_name }}</li>
            {% endif %}
            {% if movie.user == user %}
            <form action="{% url 'movies:person_delete' movie.pk person.pk %}" method="POST">
              {% csrf_token %}
              <li class="list-group-item"><input type="submit" value="PERSON DELETE" class="btn"></li>
            </form>
            {% endif %}
          </ul>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    {% if graph_image %}
    <div class="info__rategrph">
      <h4>별점 그래프 <span style="font-size: 13pt;">(평균 ★{{ movie.rate }} / {{ reviews_num }}명)</span></h4>
          <img src="data:image/png;base64,{{ graph_image }}" alt="Rate Distribution Graph">
    </div>
    {% endif %}
    <div class="info__reviews">
      <h4>리뷰</h4>
      <div class="owl-carousel owl-theme">
        {% for review in reviews %}
          {% if review.content %}
            <div class="card" style="width: 13rem; padding: 0;">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <a href="{% url 'accounts:profile' review.user.username %}">{{ review.user.username }}</a>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'reviews:detail' movie.pk review.pk %}">{{ review.content }}</a>
                </li>
                <li class="list-group-item">
                  {% if review.user == user %}
                  <form action="{% url 'reviews:delete' movie.pk review.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="DELETE" class="btn">
                  </form>
                  {% endif %}
                </li>
              </ul>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block script %}
  <script src="{% static 'movies/owl.carousel.min.js' %}"></script>
  <script>
  $('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        992:{
            items:3
        },
        1200:{
            items:4
        },
        1400:{
            items:5
        }
    }
  })

  const form = document.querySelector('#wish-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  form.addEventListener('submit', function (event) {
    event.preventDefault()
    const movieId = event.target.dataset.movieId
    axios({
      method: 'post',
      url: `/movies/${movieId}/wish/`,
      headers: {'X-CSRFToken': csrftoken,}
    })
      .then((response) => {
        const isWished = response.data.is_wished
        const wishBtn = document.querySelector('#wish-form > input[type=submit]')
        if (isWished === true) {
          wishBtn.value = 'NOT WISH'
        } else {
          wishBtn.value = 'WISH'
        }
      })
  })
</script>
{% endblock script %}