FILMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/movies/')),
    path('movies/', include('movies.urls')),
    path('magazines/', include('magazines.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

magazines/urls.py
from django.urls import path
from . import views

app_name = 'magazines'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:magazine_id>/', views.detail, name='detail'),
    path('<int:magazine_id>/delete/', views.delete, name='delete'),
    path('<int:magazine_id>/update/', views.update, name='update'),
    path('<int:magazine_id>/movie/', views.mgzn_movie, name='mgzn_movie'),
    path('<int:magazine_id>/movie/<int:movie_id>/delete/', views.mgzn_movie_delete, name='mgzn_movie_delete'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/delete/', views.delete, name='delete'),
    path('<int:movie_id>/update', views.update, name='update'),
    path('<int:movie_id>/person/', views.person, name='person'),
    path('<int:movie_id>/person/<int:person_id>/delete/', views.person_delete, name='person_delete'),
    path('<int:movie_id>/grouper_wsh/', views.grouper_wsh, name='grouper_wsh'),
    path('<int:movie_id>/wish/', views.wish, name='wish'),
    path('genre/<str:genre>', views.genre, name='genre'),
    path('country/<str:country>', views.country, name='country'),
    path('magazine/<int:magazine_id>', views.magazine, name='magazine'),
    path('every_movies/', views.every_movies, name='every_movies'),
]

magazines/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from movies.models import Movie

# Create your models here.
class Magazine(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mgzn_title = models.CharField(max_length=50, null=True, blank=True)
    def image_path(instance, filename):
        return f'magazines/{instance.mgzn_title}/{filename}'
    cover = models.ImageField(upload_to=image_path)
    cover_thumbnail = ImageSpecField(source='cover',
                                      processors=[Thumbnail(200, 260)],
                                      format='JPEG',
                                      options={'quality': 100})
    publish_date = models.DateField(null=True, blank=True)
    official = models.URLField(null=True, blank=True)
    where_to_buy = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class MagazineMovie(models.Model):
    magazine = models.ForeignKey(Magazine, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

magazines/forms.py
from .models import Magazine, MagazineMovie
from movies.models import Movie
from django import forms

class MagazineForm(forms.ModelForm):
    mgzn_title = forms.CharField(
        label = '잡지명',
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder' : '잡지명을 입력하세요',
            }
        )
    )
    cover = forms.ImageField(
        label = '잡지커버',
        widget = forms.ClearableFileInput(
            attrs = {
                'class': 'form-control',
                'multiple': True,
            },
        ),
        required = False,
    )
    publish_date = forms.DateField(
        label = '발행일',
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        ),
    )
    official = forms.URLField(
        label = '공식 사이트',
        required = False,
        widget = forms.URLInput(
            attrs = {
                'class': 'form-control'
            }
        )
    )
    where_to_buy = forms.URLField(
        label = '구매처',
        required = False,
        widget = forms.URLInput(
            attrs = {
                'class': 'form-control'
            }
        )
    )
    class Meta:
        model = Magazine
        fields = ('mgzn_title', 'cover', 'publish_date','official', 'where_to_buy')

class MagazineMovieForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        queryset=Movie.objects.all(),
        to_field_name='title'
    )
    class Meta:
        model = MagazineMovie
        fields = ('movie',)

magazines/views.py
from django.shortcuts import render, redirect
from .models import Magazine, MagazineMovie, Movie
from .forms import MagazineForm, MagazineMovieForm

# Create your views here.
def create(request):
    if request.method == "POST":
        magazine_form = MagazineForm(request.POST, request.FILES)
        if magazine_form.is_valid():
            magazine = magazine_form.save(commit=False)
            magazine.user = request.user
            magazine.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        magazine_form = MagazineForm()
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
        
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine_form': magazine_form,
    }
    return render(request, 'magazines/create.html', context)

def detail(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    movies = magazine.magazinemovie_set.all()
    mgzn_movies = [movie.movie for movie in movies]
    movies_country = Movie.objects.all().order_by('country')
    movies_genre = Movie.objects.all().order_by('genre')
    magazines = Magazine.objects.all()
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine': magazine,
        'mgzn_movies': mgzn_movies,
    }
    return render(request, 'magazines/detail.html', context)

def delete(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.user == magazine.user:
        magazine.delete()
    return redirect('movies:index')

def update(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.method == "POST":
        update_form = MagazineForm(request.POST, request.FILES, instance=magazine)
        if update_form.is_valid():
            update = update_form.save(commit=False)
            update.user = request.user
            update.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        update_form = MagazineForm(instance=magazine)
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'update_form': update_form,
        'magazine': magazine,
    }
    return render(request, 'magazines/update.html', context)
    

def mgzn_movie(request, magazine_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    if request.method=="POST":
        mgzn_movie_form = MagazineMovieForm(request.POST)
        if mgzn_movie_form.is_valid():
            mgzn_movie = mgzn_movie_form.save(commit=False)
            mgzn_movie.magazine = magazine
            mgzn_movie.save()
            return redirect('magazines:detail', magazine.pk)
    else:
        mgzn_movie_form = MagazineMovieForm()
        movies_country = Movie.objects.all().order_by('country')
        movies_genre = Movie.objects.all().order_by('genre')
        magazines = Magazine.objects.all()
        
    context = {
        'magazines': magazines,
        'movies_genre': movies_genre,
        'movies_country': movies_country,
        'magazine': magazine,
        'mgzn_movie_form': mgzn_movie_form,
    }
    return render(request, 'magazines/mgzn_movie.html', context)

def mgzn_movie_delete(request, magazine_id, movie_id):
    magazine = Magazine.objects.get(pk=magazine_id)
    mgzn_movie = MagazineMovie.objects.get(movie_id=movie_id)
    if request.user == magazine.user:
        mgzn_movie.delete()
    return redirect('magazines:detail', magazine.pk)

magazines/templates/magazines/create.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<form action="{% url 'magazines:create' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% for field in magazine_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <div class="d-grid gap-2 mb-2">
    <input type="submit" class="btn btn-primary" value="CREATE">
  </div>
</form>
{% endblock content %}

magazines/templates/magazines/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<div class="row">
  <div class="card mb-3" style="width: 20rem;">
    <img class="card-img-top" src="{{ magazine.cover_thumbnail.url }}" alt="">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">제목 : {{ magazine.mgzn_title }}</li>
      <li class="list-group-item">발행일 : {{ magazine.publish_date }}</li>
      <li class="list-group-item">공식 사이트 : <a href="{{ magazine.official }}">{{ magazine.official }}</a></li>
      <li class="list-group-item">구매처 : <a href="{{ magazine.where_to_buy }}">{{ magazine.where_to_buy }}</a></li>
    </ul>
  </div>
  {% for movie in mgzn_movies %}
  <div class="card mb-3" style="width: 14rem;">
    <img class="card-img-top" src="{{ movie.poster_thumbnail.url }}" alt="">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">제목 : {{ movie.title }}</li>
      <li class="list-group-item">원제 : {{ movie.original_title }}</li>
      <li class="list-group-item">개봉일 : {{ movie.release_date }}</li>
      <li class="list-group-item">장르 : {{ movie.genre }}</li>
      <li class="list-group-item">국가 : {{ movie.country }}</li>
      <li class="list-group-item">연령 : {{ movie.age }}</li>
    </ul>
    <form action="{% url 'magazines:mgzn_movie_delete' magazine.pk movie.pk %}" method="POST">
      {% csrf_token %}
      <li class="list-group-item"><input type="submit" value="MGZN MOVIE DELETE" class="btn btn-primary"></li>
    </form>
  </div>
  {% endfor %}
  <div class="d-grid gap-2 d-flex mb-3">
    {% if magazine.user == user %}
    <form action="{% url 'magazines:delete' magazine.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE" class="btn btn-primary">
    </form>
    <a href="{% url 'magazines:update' magazine.pk %}" class="btn btn-primary">UPDATE</a>
    <a href="{% url 'magazines:mgzn_movie' magazine.pk %}" class="btn btn-primary">MGZN MOVIE</a>
    {% endif %}
  </div>
</div>
{% endblock content %}

magazines/templates/magazines/mgzn_movie.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<form action="{% url 'magazines:mgzn_movie' magazine.pk %}" method="POST">
  {% csrf_token %}
  {% for field in mgzn_movie_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <div class="d-grid gap-2 mb-2">
    <input type="submit" class="btn btn-primary" value="MGZN MOVIE">
    <a href="{% url 'movies:create' %}" class="btn btn-info btn-fill pull-right">영화등록</a>
  </div>
</form>
{% endblock content %}

magazines/templates/magazines/update.html
{% extends 'base.html' %}

{% block style %}
<style>
  body {
    margin: 5rem;
  }
</style>
{% endblock style %}

{% block content %}
<form action="{% url 'magazines:update' magazine.pk %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% for field in update_form %}
  <div class="input-group mb-3">
    <span class="input-group-text" style = "width: 13rem;" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div> 
  {% endfor %}
  <div class="d-grid gap-2 mb-2">
    <input type="submit" class="btn btn-primary" value="UPDATE">
  </div>
</form>
{% endblock content %}