FILMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/movies/')),
    path('movies/', include('movies.urls')),
    path('magazines/', include('magazines.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

magazines/urls.py
from django.urls import path
from . import views

app_name = 'magazines'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:magazine_id>/', views.detail, name='detail'),
    path('<int:magazine_id>/delete/', views.delete, name='delete'),
    path('<int:magazine_id>/update/', views.update, name='update'),
    path('<int:magazine_id>/movie/', views.mgzn_movie, name='mgzn_movie'),
    path('<int:magazine_id>/movie/<int:movie_id>/delete/', views.mgzn_movie_delete, name='mgzn_movie_delete'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('<int:movie_id>/delete/', views.delete, name='delete'),
    path('<int:movie_id>/update', views.update, name='update'),
    path('<int:movie_id>/person/', views.person, name='person'),
    path('<int:movie_id>/person/<int:person_id>/delete/', views.person_delete, name='person_delete'),
    path('<int:movie_id>/grouper_wsh/', views.grouper_wsh, name='grouper_wsh'),
    path('<int:movie_id>/wish/', views.wish, name='wish'),
    path('genre/<str:genre>', views.genre, name='genre'),
    path('country/<str:country>', views.country, name='country'),
    path('magazine/<int:magazine_id>', views.magazine, name='magazine'),
    path('every_movies/', views.every_movies, name='every_movies'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    {% block head %}{% endblock head %}
    <title>Document</title>
    <style>
      html, body {
        width: 100%;
        height: 100%;
      }

      .wrapper {
        height : auto;
        min-height: 100%;
        padding-bottom: 150px;
        margin-bottom: 30px;
      }

      * {
        font-family: 'Gowun Batang', serif;
        
      }

      a {
        text-decoration-line: none;
        color: #3aa159;
      }


      .navbar-brand {
        font-weight: 500;
      }

      .navbar-custom {
        box-shadow: 0 4px 11px rgba(0,0,0,0.1);
        {% block nav_bg %}{% endblock nav_bg %}
      }

      .nav__personal-item {
        margin-right: 10px;
      }

      .body__main {
        margin-top: 30px;
      }

      .card {
        border: 0;
      }

      .btn {
        background-color: #3aa159;
        border-color: #3aa159;
        color: white;
      }

      .btn:hover {
        background-color: white;
        border-color: #3aa159;
        color: #3aa159;
      }
      
      .footer__container {
        height: 150px;
        position : relative;
        background-color: #3aa159;
        padding: 2rem 1rem 2rem 1rem;
        position: relative;
        margin-top: -150px;
      }
      
      .footer__creators {
        color: white;
        list-style-type: none;
        text-decoration: none;
        padding: 0;
      }
      
      .footer__copyrights {
        color: white;
        border-top: 1px solid white;
      }
      {% block style %}
      {% endblock style %}
    </style>
  </head>
  <body>
    <div class="wrapper">
      <nav class="navbar navbar-custom navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid nav__container">
          <a class="navbar-brand fs-3" href="{% url 'movies:index' %}">
            <img src="{% static 'ICON_CLR.png' %}" alt="ICON_CLR" width="40" height="40" class="d-inline-block align-center">
            FILMArchive
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'movies:every_movies' %}">영화</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  잡지
                </a>
                <ul class="dropdown-menu">
                  {% for magazine in magazines %}
                  <li><a class="dropdown-item" href="{% url 'movies:magazine' magazine.pk %}">{{ magazine.mgzn_title }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  장르별
                </a>
                <ul class="dropdown-menu">
                  {% regroup movies_genre by genre as genre_list %}
                  {% for genre in genre_list %}
                  <li><a class="dropdown-item" href="{% url 'movies:genre' genre.grouper %}">{{ genre.grouper }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  국가별
                </a>
                <ul class="dropdown-menu">
                  {% regroup movies_country by country as country_list %}
                  {% for country in country_list %}
                  <li><a class="dropdown-item" href="{% url 'movies:country' country.grouper %}">{{ country.grouper }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            </ul>
            <ul class="nav__personal navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              {% if user.is_authenticated %}
              <li class="nav__personal-item"><a href="{% url 'accounts:profile' user.username %}"><span style="color: black;">{{ user }}</span>의 프로필</a></li>
              <li class="nav__personal-item"><a href="{% url 'accounts:update' %}">내정보수정</a></li>
              <li class="nav__personal-item"><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
              <li class="nav__personal-item"><a href="{% url 'accounts:delete' %}">회원탈퇴</a></li>
              <li class="nav__personal-item"><a href="{% url 'movies:create' %}" style="color: grey;">영화등록</a></li>
              <li class="nav__personal-item"><a href="{% url 'magazines:create' %}" style="color: grey;">잡지등록</a></li>
              {% else %}
              <li class="nav__personal-item"><a href="{% url 'accounts:login' %}">로그인</a></li>
              <li class="nav__personal-item"><a href="{% url 'accounts:signup' %}">회원가입</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <div class="body__main container">
        {% block content %}
        {% endblock content %}
      </div>

    </div>
    
    <footer class="footer__container">
      <div class="row">
        <div class="col col-md-10">
          <p class="fs-4" style="color: white;">Watch, Read, Be Fulfilled.</p>
        </div>
        <div class="col-auto col-md-2">
          <div class="footer__creators d-flex gap-2">
            <li><a href="">
              <img src="{% static 'ICON_WHITE.png' %}" alt="" style="width: 30px;">
            </a></li>
            <li><a href="https://github.com/ssongnoss66">
              <img src="{% static 'github-mark-white.png' %}" alt="" style="width: 30px;">
            </a></li>
            <li><a href="https://www.instagram.com/dev.ssong_/">
              <img src="{% static 'insta.png' %}" alt="" style="width: 30px;">
            </a></li>
          </div>
        </div>
        <div class="footer__copyrights">
          <span>© 2023 FILMArchive Co., Ltd. All rights reserved.</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'jquery.min.js' %}"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>